apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  selector:
    app: calculator   # Ensure this selector matches your Deployment's labels
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # Target port where your application is running
  type: LoadBalancer  # If you want to expose externally in Minikube

